esphome:
  name: esphome-sacredsun
  friendly_name: esphome-sacredsun

external_components:
  - source: github://wire67/esphome_sacredsun_rs485@components
    refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret sacredsun_api_encr_key

ota:
  - platform: esphome
    password: !secret sacredsun_ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esphome-sacredsun"
    password: !secret sacredsun_wifi_ap_pwd

captive_portal:

uart:
  tx_pin: GPIO22
  rx_pin: GPIO23
  baud_rate: 9600
  id: uart_bus

sacredsun_rs485:
  uart_id: uart_bus
  send_interval: 4000
  pack_count: 2

sensor:
  - platform: sacredsun_rs485
    pack: 0
    sensors:
      - name: "Pack 1 SOC"
        id: pack_1_soc
        type: soc
        unit_of_measurement: "%"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 1 Voltage"
        id: pack_1_voltage
        type: voltage
        unit_of_measurement: "V"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 1 Current"
        id: pack_1_current
        type: current
        unit_of_measurement: "A"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 1 SOH"
        id: pack_1_soh
        type: soh
        unit_of_measurement: "%"
      - name: "Pack 1 Nominal Capacity"
        id: pack_1_nominal_cap
        type: nominal_cap
        unit_of_measurement: "Ah"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 1 Remaining Capacity"
        id: pack_1_remaining_cap
        type: remaining_cap
        unit_of_measurement: "Ah"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 1 Cycles"
        id: pack_1_cycles
        type: cycles
        unit_of_measurement: "times"
        accuracy_decimals: 0

  - platform: sacredsun_rs485
    pack: 1
    sensors:
      - name: "Pack 2 SOC"
        id: pack_2_soc
        type: soc
        unit_of_measurement: "%"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 2 Voltage"
        id: pack_2_voltage
        type: voltage
        unit_of_measurement: "V"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 2 Current"
        id: pack_2_current
        type: current
        unit_of_measurement: "A"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 2 SOH"
        id: pack_2_soh
        type: soh
        unit_of_measurement: "%"
      - name: "Pack 2 Nominal Capacity"
        id: pack_2_nominal_cap
        type: nominal_cap
        unit_of_measurement: "Ah"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 2 Remaining Capacity"
        id: pack_2_remaining_cap
        type: remaining_cap
        unit_of_measurement: "Ah"
        accuracy_decimals: 2
        filters:
          - multiply: 0.01
      - name: "Pack 2 Cycles"
        id: pack_2_cycles
        type: cycles
        unit_of_measurement: "times"
        accuracy_decimals: 0